pop_records<-readLines("C:/Users/lauje/Downloads/CO2_DataFinal_V3 (1).csv")
pop_data<-read.csv("C:/Users/lauje/Downloads/CO2_DataFinal_V3 (1).csv")
str(pop_data)
library(rworldmap)
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
map_data<-joinCountryData2Map(pop_data,joinCode = "ISO3",nameJoinColumn = "Code")
mapCountryData(map_data,nameColumnToPlot = "ICT")
mapCountryData(map_data,nameColumnToPlot = "CL")
mapCountryData(map_data,nameColumnToPlot = "CO2")
mapCountryData(map_data,nameColumnToPlot = "GDPP")
mapCountryData(map_data,nameColumnToPlot = "Stability")
mapCountryData(map_data,nameColumnToPlot = "Education")
mapCountryData(map_data,nameColumnToPlot = "Resistance")
mapCountryData(map_data,nameColumnToPlot = "PR")
